city:
  name: Karachi
  lat: 24.8607
  lon: 67.0011

api:
  aqi_url: "https://api.waqi.info/feed/karachi/"
  aqi_key: "5c8119e019240a0ca24b366f9a276b6baaabcb31"
  weather_url: "https://api.openweathermap.org/data/2.5/weather"
  weather_key: "39b201e26d98485314a560495765b940"

hopsworks:
  api_key: "GJh2A4GzI7pr7lhh.CXvriR2G7NYp74YsodVBUhWiY0Zn86jpLFyGVcKxkf7xjvELQkAX2Nt1vH6MbDAV"

alerts:
  aqi_threshold: 150
  sender_email: "Huzaifa22.edu.pk@gmail.com"
  sender_password: "APP_PASSWORD"
  receiver_email: "z04669289@gmail.com"