api:
  weather_key: "39b201e26d98485314a560495765b940"

location:
  lat: 24.8607
  lon: 67.0011

hopsworks:
  api_key: "xPZvN12qyepFH78l.gGJQYiPQplzZA4jJmK2SyNTqRa4QF1oZ6wCGKz1SxJWXjWHYmLbMASLvMj0bxeZc"