name: Hourly Feature Pipeline

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  feature_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create config.yaml from secrets
        run: |
          mkdir -p config
          cat <<EOF > config/config.yaml
          hopsworks:
            api_key: "${{ secrets.HOPSWORKS_API_KEY }}"

          city:
            name: "Karachi"
            lat: 24.8607
            lon: 67.0011

          api:
            weather_url: "https://api.openweathermap.org/data/2.5/weather"
            air_pollution_url: "https://api.openweathermap.org/data/2.5/air_pollution"
            weather_key: "${{ secrets.WEATHER_API_KEY }}"
          EOF

      - name: Run ingestion + feature pipeline
        env:
          PYTHONPATH: .
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          python ingestion/fetch_data.py
          python features/feature_engineering.py