HOPSWORKS_HOST = "eu-west.cloud.hopsworks.ai"
HOPSWORKS_API_KEY = "GJh2A4GzI7pr7lhh.CXvriR2G7NYp74YsodVBUhWiY0Zn86jpLFyGVcKxkf7xjvELQkAX2Nt1vH6MbDAV"
WEATHER_API_KEY = "39b201e26d98485314a560495765b940"